### ISSUE TITLE
Backend sends undocumented SQs with `fixedCriteria` and `primaryCode` 

### ISSUE THREAD

**Issue by tobiasgirardet** [medizininformatik-initiative/feasibility-backend#121]
Since the last update, the FDPG sends Structured Queries to the different sites that contain new elements such as `fixedCriteria` and `primaryCode` that are not documented in the respective repository [1].

In addition, the version of the sent queries is still 

` "version":"http://to_be_decided.com/draft-1/schema#"`

Therefore, the queries cannot be validated against the schema published in [1].

It is for us of utmost importance that we know exactly how the interface between external systems and our internal systems is working, otherwise we cannot check if we are compliant with our own operational concept.

[1]  https://github.com/medizininformatik-initiative/feasibility-structured-query

**Comment by tobiasgirardet** [comment]
cc @nickamzol

**Comment by juliangruendner** [comment]
@tobiasgirardet  - not part of the backend - this is a mapping and SQ issue an will be handled in these repositories.
