### ISSUE TITLE
Endpoint Modification for Template and savedQueries Retrieval with activated Validation

### ISSUE THREAD

**Issue by thkoehler11** [medizininformatik-initiative/feasibility-backend#260]
Issue: Endpoint Modification for Template and savedQueries Retrieval with Activated Validation

- There's a modification in the endpoint for template retrieval, transitioning to `/query/template` with activated validation. Additionally, an optional URL parameter `?validate=false` is introduced to deactivate the validation process

- The retrieval process for 'savedQueries' follows the same schema as the modification in the endpoint for template retrieval.

**Comment by michael-82** [comment]
This will most likely become v4 of the api unless agreed upon otherwise
