### ISSUE TITLE
Disabling Keycloak Causes NPE

### ISSUE THREAD

**Issue by DiCanio** [medizininformatik-initiative/feasibility-backend#27]
Disabling Keycloak functionality using the `KEYCLOAK_ENABLED` environment variable has no effect other than a NullPointerException on endpoints that require principal information.

This requires a decision on an architectural level since user information is mandatory. In the past, disabling Keycloak has been reserved for development purposes anyway. Thus, dropping this switch altogether seems to be reasonable.

**Comment by juliangruendner** [comment]
not relevant anymore as keycloak cannot be disabled anymore
