### ISSUE TITLE
Load availability files from file(s)

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#288]
The availability counts which are created by the fhir-data-evaluator should be used by the backend and the ontology elastic search.

The availability counts can update more often than ontology itself the elastic search data will be based on. Therefore a program should be created which allows the additional loading of the availability data.

See also the following issue: https://github.com/medizininformatik-initiative/feasibility-ontology-elasticsearch/issues/3

The backend should then be extended to allow the dynamic updating of the availability on the fly:

TODO: @michael-82 

Look into how elastic search indices can be updated on the fly and make a suggestion of how this can be implemented in the backend and elastic search, so that given a file to with the availability information the elastic search availability for each criteron can be updated and re-indexed.

**Comment by michael-82** [comment]
As discussed yesterday, this will be a plain script, separated from the backend application (but in this repository). This can not be reasonably executed by anyone but "us" since the necessary availability data may not be public
