### ISSUE TITLE
Initialise elastic search as part of a standard deployment

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#289]
Elastic search in a specific version should be initialised as part of the deployment of the backend. 
This means that the correct elastic search load file should be part of the backend ontology read on startup.

This issue is dependent on this issue of the fhir-ontology-generator: https://github.com/medizininformatik-initiative/fhir-ontology-generator/issues/29

**Comment by michael-82** [comment]
Just to clarify...is the following assumption correct?

1. The files necessary to create the index in elastic search and then fill it with the current (at that point of time) documents will be included in the backend.zip file from the ontology generator
2. Those files will be packaged with the docker image (equivalent to the database migration script containing the ui profiles)
3. On startup, it will be checked if the index is present and at the exact same version - if not, it will be (if necessary) deleted and newly created? Or will it throw an error and deny starting?
4. There will **not** be a download of those files during backend startup
5. Changes to the elastic search index will require new images to be built and deployed. (Not the changes to the availability, but to the mapping or general content)

**Comment by juliangruendner** [comment]
1. yes
2. yes
3. delete and create new
4. yes
5. yes
