### ISSUE TITLE
OPS are not exhaustively searchable.

### ISSUE THREAD

**Issue by geloro94** [medizininformatik-initiative/feasibility-backend#292]
Expected Behavior: Entering any code should return the expected concept. 

Current Behavior: 5-793.k or 5-793.kr are not findable when entered in the search. This seems to be a recurring issue with all OPS codes having the pattern X-XXX.* only X-XXX is findable.

**Comment by michael-82** [comment]
The issue is the search being case-sensitive in the backend and the frontend apparently capitalizing all search terms. I see no good reason for the search to be case-sensitive.
