### ISSUE TITLE
Multiple repeatable DB migrations

### ISSUE THREAD

**Issue by michael-82** [medizininformatik-initiative/feasibility-backend#312]
Currently with only one db migration script (loading the ui profiles) it is feasible to have a script clean the db beforehand.
With two seperate scripts, this is no longer an option, since flyway only executes those scripts that have changed. And if only one has changed, the data from the other would be missing.

**Comment by michael-82** [comment]
I currently see no other option than including the corresponding DELETE statements to the repeatable DB dump files themselves.
When trying to use callback scripts from flyway to execute, there is no way (or at least I did not find the way) to get a list of queued repeatable migrations for this run, so that you could programmatically either delete ids < 100000 or > 10000.

When simply trying to set the checksums for the already applied repeatable migrations to 0, this does not lead to both scripts being executed because apparently, the list of migrations to run is compiled before calling this script.

**Comment by juliangruendner** [comment]
@michael-82  - closing this issue as no longer relevant - will be resolved through https://github.com/medizininformatik-initiative/fhir-ontology-generator/issues/18 instead
