### ISSUE TITLE
Add endpoints for profile data

### ISSUE THREAD

**Issue by michael-82** [medizininformatik-initiative/feasibility-backend#318]
The following is needed in order to support the upcoming DSE feature.

1. /dse/profile-tree
2. /dse/profile-data
~3. /terminology/i18n~
3. /terminology/systems

1) simply deliveres a pre-generated json (https://github.com/medizininformatik-initiative/fdpg-plus/issues/18)
2) takes a list of urls (or maybe uuids...to be discussed with gui team) and returns the detailed information for those ids (similar to the criteria-profile-data endpoint). This information is to be stored in a standalone table in the postgres db
3) returns a mapping between the terminology url and a better readable name (e.g. simply "loinc") ~- since this does not need different languages (most likely), it could be renamed to something that does not imply multiple languages~

**Comment by juliangruendner** [comment]
/terminology/i18n change to /terminology/systems
