### ISSUE TITLE
Search for Code with "." not working

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#365]
A Search for a code with a "." in it is currently not supported.

IS:
search for I95.0 returns nothing

SHOULD:
search for I95.0 should return the criterion I95.0

This is the same for any code with a . in it

**Comment by michael-82** [comment]
This is an issue of the index creation (which is done in the fhir ontology generator)

[linked issue](https://github.com/medizininformatik-initiative/fhir-ontology-generator/issues/69)
