### ISSUE TITLE
Add endpoint to check for possible criteria links

### ISSUE THREAD

**Issue by michael-82** [medizininformatik-initiative/feasibility-backend#38]
In order to allow to link search criteria with others (e.g. linking a specimen to a diagnosis), an option is needed for the GUI to check whether or not some elements are candidates to be linked.

The endpoint receives a json object containing the current "parent" node (defined by its termCode and attributeCodes) as well as a list of other nodes to check (defined by their termCodes and ui-defined ids)

It retuns a list of elements that can be linked, specified by the id that was supplied.

Example (the keys are just working titles):

GET .../terminology/reference-options

```
{
   "parent": {
   	"termcode": {
   		"system":...
   		"code":...
   		// basically system and code should suffice, but there's no harm in just sending the whole termcode object
   	},
   	"attributeCodes": [
   		{
   			// attribute code1
   		},
   		{
   			// attribute code2
   		},
   		...  // attribute code n
   	]
   },
   "selectedTerms": [
   	{
   		"uiIndex": "1:1",
	   	"termcode": {
	   		"system":...
	   		"code":...
	   		// optional: rest of termCode
	   	}
   	},
   	   	{
   		"uiIndex": "2:1",
	   	"termcode": {
	   		"system":...
	   		"code":...
	   		// optional: rest of termCode
	   	}
   	},
   	... // any amount
   ]
}
```
---> 200 OK

```
{
	"referenceCandidateIds": ["1:1"]
}
```

**Comment by juliangruendner** [comment]
close issue - as this version is outdated
