### ISSUE TITLE
Migrate from Keycloak Adapter to Spring Security OAuth

### ISSUE THREAD

**Issue by alexanderkiel** [medizininformatik-initiative/feasibility-backend#53]
We need this for the upgrade to Spring 6 (#54).

https://stackoverflow.com/questions/74571191/use-keycloak-spring-adapter-with-spring-boot-3

The update to spring 6 will also be included here (was #54)

**Comment by michael-82** [comment]
The update to spring 6 contains the switch to jakarta. With the currently released version of dsf (0.9.0) this is not working.

By modifying the parts of dsf required here (fhir-webclient), it is running again (https://github.com/michael-82/highmed-dsf/tree/jakarta-migration does this..but it **breaks other parts of dsf** and thus can not be considered a real alternative)
