### ISSUE TITLE
Limit result polling 

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#59]
The time between the polling of results should be limited per user to a configurable amount of time in seconds.

This should be applied to all query "result" endpoints except the admin protected one which returns the un-obfuscated site names of a query.

If a user polls more often than the configured amount of time the endpoint should instead return a 429 - Too Many Requests

The time between polling should be calculated based on the last time an result was returned.

Example:
If the amount of time seconds between polling requests is 10 seconds
and a user polls every 5 seconds starting from 0.
0 = return result
5 = return 429 - Too Many Requests
10 = return result
15 return 429 - Too Many Requests

**Comment by michael-82** [comment]
We also need a differentiation between general result polling and polling results with per-site results (on different times/amounts)
