### ISSUE TITLE
Limit requesting of detailed results per user

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-backend#68]
The number of times a user is allowed to call the detailed-obfuscated-result  (with the site names obfuscated in the detailed result) should be limited to 
x number of times per y number of hours.

This should be applied to the detailed query result endpoint and for each user individually.

If a user calls the endpoint more often than the configured amount per time the endpoint should instead return a 429 - Too Many Requests

The number of times the endpoint was called should only be increased if a result is returned.

**Comment by michael-82** [comment]
Closed by #77
