### ISSUE TITLE
Exceptions in the CQL translation should not result in discarding the query.

### ISSUE THREAD

**Issue by geloro94** [medizininformatik-initiative/feasibility-backend#8]
"cannot translate structured query to CQL format" Exception cause for example if a mapping is missing for the codesystem alias should not result in discarding the query. The SQ should still be forwarded to sites that use the SQ format and not CQL.

**Comment by DiCanio** [comment]
This is a problem on an architectural level.

We decided to send every possible format to every site when running a decentralized query. Each site then uses only the format that fits its configuration.
Reason for this is that there is no communication between each site and the centralized part of the application that would allow us to identify which format needs to be sent to which site.

If we were to have some kind of registration process in place then each site would be able to register for decentralized query executions telling the central part of the application which format it requires.
Furthermore, such a process would also come in handy when trying to tackle the issue of trying to determine when a query has finished (all participants are known up front).

Thus, I think this is currently not possible to implement without bigger adjustments.
